import csv
import io
from fastapi import APIRouter, Depends
from fastapi.responses import StreamingResponse, PlainTextResponse
from sqlalchemy.orm import Session
from sqlalchemy import text
from uuid import UUID
from app.database import get_db
from app.models.loan import Loan
from app.models.payment import Payment

router = APIRouter()

# ── Export all loans to CSV ───────────────────
@router.get("/loans/csv")
def export_loans_csv(db: Session = Depends(get_db)):
    rows = db.execute(text("SELECT * FROM v_loan_summary ORDER BY date_issued DESC")).mappings().all()

    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow([
        'Person', 'Direction', 'Principal', 'Currency', 'Interest Rate',
        'Interest Type', 'Period', 'Date Issued', 'Due Date', 'Status',
        'Total Paid', 'Total Interest', 'Balance Due', 'Purpose', 'Days Overdue'
    ])
    for r in rows:
        writer.writerow([
            r['person_name'], r['direction'], r['principal'], r['currency'],
            r['interest_rate'], r['interest_type'], r['interest_period'],
            r['date_issued'], r['due_date'], r['status'],
            r['total_paid'], r['total_interest'], r['balance_due'],
            r['purpose'] or '', r['days_overdue'] or 0
        ])

    output.seek(0)
    return StreamingResponse(
        iter([output.getvalue()]),
        media_type="text/csv",
        headers={"Content-Disposition": "attachment; filename=loans_export.csv"}
    )

# ── Export payments for a loan to CSV ────────
@router.get("/loans/{loan_id}/payments/csv")
def export_payments_csv(loan_id: UUID, db: Session = Depends(get_db)):
    loan = db.query(Loan).filter(Loan.id == loan_id).first()
    if not loan:
        return PlainTextResponse("Loan not found", status_code=404)

    payments = db.query(Payment).filter(Payment.loan_id == loan_id)\
        .order_by(Payment.payment_date).all()

    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(['Date', 'Amount', 'Currency', 'Method', 'Reference', 'Notes'])
    for p in payments:
        writer.writerow([
            p.payment_date, p.amount, loan.currency,
            p.method, p.reference or '', p.notes or ''
        ])

    output.seek(0)
    return StreamingResponse(
        iter([output.getvalue()]),
        media_type="text/csv",
        headers={"Content-Disposition": f"attachment; filename=payments_{loan_id}.csv"}
    )

# ── Loan statement as text ────────────────────
@router.get("/loans/{loan_id}/statement")
def loan_statement(loan_id: UUID, db: Session = Depends(get_db)):
    loan = db.execute(
        text("SELECT * FROM v_loan_summary WHERE id = :id"),
        {"id": str(loan_id)}
    ).mappings().first()

    if not loan:
        return PlainTextResponse("Loan not found", status_code=404)

    payments = db.query(Payment).filter(Payment.loan_id == loan_id)\
        .order_by(Payment.payment_date).all()

    lines = [
        "=" * 55,
        "         PERSONAL LOAN STATEMENT",
        "=" * 55,
        f"Person       : {loan['person_name']}",
        f"Direction    : {loan['direction'].upper()}",
        f"Principal    : {loan['currency']} {loan['principal']}",
        f"Interest     : {loan['interest_rate']}% {loan['interest_type']} ({loan['interest_period']})",
        f"Date Issued  : {loan['date_issued']}",
        f"Due Date     : {loan['due_date'] or 'Open-ended'}",
        f"Status       : {loan['status'].upper()}",
        f"Purpose      : {loan['purpose'] or '—'}",
        "-" * 55,
        f"Total Interest : {loan['currency']} {loan['total_interest']}",
        f"Total Paid     : {loan['currency']} {loan['total_paid']}",
        f"Balance Due    : {loan['currency']} {loan['balance_due']}",
        "-" * 55,
        f"PAYMENT HISTORY ({len(payments)} payments)",
        "-" * 55,
    ]

    if payments:
        for p in payments:
            lines.append(
                f"  {p.payment_date}  {loan['currency']} {p.amount:>10}  "
                f"{p.method:<16}  {p.reference or ''}"
            )
    else:
        lines.append("  No payments recorded yet.")

    if loan['days_overdue']:
        lines += [
            "-" * 55,
            f"⚠️  OVERDUE BY {loan['days_overdue']} DAYS",
        ]

    lines += ["=" * 55, "Generated by Personal Loan Tracker", "=" * 55]

    content = "\n".join(lines)
    return StreamingResponse(
        iter([content]),
        media_type="text/plain",
        headers={"Content-Disposition": f"attachment; filename=statement_{loan_id}.txt"}
    )

# ── Full data export (JSON) ───────────────────
@router.get("/full-backup")
def full_backup(db: Session = Depends(get_db)):
    import json
    from datetime import date, datetime

    def serial(obj):
        if isinstance(obj, (date, datetime)):
            return obj.isoformat()
        return str(obj)

    loans    = db.execute(text("SELECT * FROM v_loan_summary")).mappings().all()
    persons  = db.execute(text("SELECT * FROM persons")).mappings().all()
    payments = db.execute(text("SELECT * FROM payments ORDER BY payment_date")).mappings().all()

    data = {
        "exported_at": datetime.now().isoformat(),
        "persons":     [dict(r) for r in persons],
        "loans":       [dict(r) for r in loans],
        "payments":    [dict(r) for r in payments],
    }

    content = json.dumps(data, default=serial, indent=2)
    return StreamingResponse(
        iter([content]),
        media_type="application/json",
        headers={"Content-Disposition": "attachment; filename=loan_tracker_backup.json"}
    )
